# Generated by Django 4.2.5 on 2023-09-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('og_url', models.URLField(max_length=300)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=50)),
            ],
        ),
    ]
